[2024-11-28T11:12:42.981+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: snowflake_demo_dag.create_table manual__2024-11-28T11:12:41.823493+00:00 [queued]>
[2024-11-28T11:12:42.986+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: snowflake_demo_dag.create_table manual__2024-11-28T11:12:41.823493+00:00 [queued]>
[2024-11-28T11:12:42.986+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T11:12:42.986+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 11
[2024-11-28T11:12:42.986+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T11:12:42.992+0000] {taskinstance.py:1383} INFO - Executing <Task(SnowflakeOperator): create_table> on 2024-11-28 11:12:41.823493+00:00
[2024-11-28T11:12:42.995+0000] {standard_task_runner.py:55} INFO - Started process 792 to run task
[2024-11-28T11:12:42.997+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'snowflake_demo_dag', 'create_table', 'manual__2024-11-28T11:12:41.823493+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_dag.py', '--cfg-path', '/tmp/tmpc8ar0t3z']
[2024-11-28T11:12:42.997+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask create_table
[2024-11-28T11:12:43.029+0000] {task_command.py:376} INFO - Running <TaskInstance: snowflake_demo_dag.create_table manual__2024-11-28T11:12:41.823493+00:00 [running]> on host e85eb02d191d
[2024-11-28T11:12:43.076+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=snowflake_demo_dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-11-28T11:12:41.823493+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-28T11:12:41.823493+00:00
[2024-11-28T11:12:43.077+0000] {sql.py:265} INFO - Executing: 
CREATE TABLE IF NOT EXISTS demo_table (
    id INTEGER,
    name STRING,
    created_at TIMESTAMP
);
[2024-11-28T11:12:43.081+0000] {base.py:71} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-11-28T11:12:43.400+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:109: UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  "pyarrow", installed_pyarrow_version, pandas_pyarrow_extra

[2024-11-28T11:12:43.612+0000] {base.py:71} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-11-28T11:12:43.612+0000] {connection.py:300} INFO - Snowflake Connector for Python Version: 3.0.4, Python Version: 3.7.15, Platform: Linux-6.10.4-linuxkit-aarch64-with-debian-11.5
[2024-11-28T11:12:43.613+0000] {connection.py:1013} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-28T11:12:43.613+0000] {connection.py:1023} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-11-28T11:12:43.613+0000] {connection.py:1030} INFO - Setting use_openssl_only mode to False
[2024-11-28T11:12:44.166+0000] {ssl_wrap_socket.py:101} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-11-28T11:12:44.499+0000] {cursor.py:806} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-11-28T11:12:44.647+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:12:44.648+0000] {cursor.py:962} INFO - Number of results in first chunk: 1
[2024-11-28T11:12:44.650+0000] {sql.py:375} INFO - Running statement: CREATE TABLE IF NOT EXISTS demo_table (
    id INTEGER,
    name STRING,
    created_at TIMESTAMP
);, parameters: None
[2024-11-28T11:12:44.651+0000] {cursor.py:806} INFO - query: [CREATE TABLE IF NOT EXISTS demo_table ( id INTEGER, name STRING, created_at TIME...]
[2024-11-28T11:12:44.849+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:12:44.850+0000] {cursor.py:962} INFO - Number of results in first chunk: 1
[2024-11-28T11:12:44.851+0000] {sql.py:384} INFO - Rows affected: 1
[2024-11-28T11:12:44.852+0000] {snowflake.py:391} INFO - Rows affected: 1
[2024-11-28T11:12:44.853+0000] {snowflake.py:392} INFO - Snowflake query id: 01b8ac00-0001-3903-0006-ac5e0001a8de
[2024-11-28T11:12:44.853+0000] {cursor.py:806} INFO - query: [COMMIT]
[2024-11-28T11:12:44.940+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:12:44.940+0000] {cursor.py:962} INFO - Number of results in first chunk: 1
[2024-11-28T11:12:44.941+0000] {connection.py:605} INFO - closed
[2024-11-28T11:12:45.065+0000] {connection.py:608} INFO - No async queries seem to be running, deleting session
[2024-11-28T11:12:45.168+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=snowflake_demo_dag, task_id=create_table, execution_date=20241128T111241, start_date=20241128T111242, end_date=20241128T111245
[2024-11-28T11:12:45.206+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-11-28T11:12:45.229+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
